### ISSUE TITLE
房间类型输错还会开房

### ISSUE THREAD

**Issue by LittleDeng1** [ratel-online/server#31]
![W`8YKYIWQ_N44@%)DX@T7IX](https://user-images.githubusercontent.com/62782358/185026847-0c933d79-2d69-4cd0-972a-5f033cae7504.png)

**Comment by mlmdflr** [comment]
#30

**Comment by mlmdflr** [comment]
下次一定

**Comment by mlmdflr** [comment]
fixed

**Comment by ainilili** [comment]
不可能，绝对不可能
