### ISSUE TITLE
德州扑克这个应该如何开玩

### ISSUE THREAD

**Issue by ilsgqy** [ratel-online/server#41]
德州扑克能玩起来吗？ 没看到教程

**Comment by ainilili** [comment]
进游戏过程和斗地主一样，创建房间，输入s开始，牌局内指令参考这里 https://github.com/ratel-online/server?tab=readme-ov-file#%E5%BE%B7%E5%B7%9E%E6%89%91%E5%85%8B%E8%A7%84%E5%88%99
